# Generated by Django 2.2.2 on 2019-07-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='eid',
            field=models.IntegerField(),
        ),
    ]
