# Generated by Django 2.2.2 on 2019-07-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_auto_20190704_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'ordering': ['-ename']},
        ),
    ]
