# Generated by Django 2.2.2 on 2019-07-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_mymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='image',
            field=models.FileField(upload_to='image/'),
        ),
    ]
