# Generated by Django 2.2.2 on 2019-07-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_auto_20190705_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('enrollment', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=21)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
