# Generated by Django 2.2.2 on 2019-07-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='csv/')),
            ],
            options={
                'db_table': 'csv',
            },
        ),
    ]
