# Generated by Django 2.2.2 on 2019-07-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_csv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='csv',
        ),
    ]
