# Generated by Django 2.2.2 on 2019-07-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_delete_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('receipt_no', models.IntegerField()),
                ('receipt_date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('student_enrollment', models.CharField(max_length=15)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('fee_receipt_image', models.FileField(upload_to='images/')),
                ('cancelled_cheque_image', models.FileField(upload_to='images/')),
            ],
            options={
                'db_table': 'transation',
            },
        ),
    ]
