# Generated by Django 2.2.2 on 2019-07-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0010_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_date',
            field=models.DateField(),
        ),
    ]
