# Generated by Django 2.2.2 on 2019-07-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_auto_20190707_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='application_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='student_enrollment',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
