# Generated by Django 2.2.2 on 2019-07-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0012_auto_20190707_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='kuchbhi@kuchbhi.com', max_length=254),
            preserve_default=False,
        ),
    ]
