# Generated by Django 2.2.2 on 2019-07-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0016_auto_20190718_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='application_no',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee_receipt_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_sem_fee_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
