# Generated by Django 2.2.2 on 2019-07-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0018_auto_20190721_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_no',
            field=models.IntegerField(null=True),
        ),
    ]
