# Generated by Django 2.2.2 on 2019-07-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0019_auto_20190721_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
