# Generated by Django 2.2.2 on 2019-07-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0020_transaction_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_date',
            field=models.DateField(blank=True),
        ),
    ]
