# Generated by Django 2.2.2 on 2019-07-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0021_auto_20190723_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
