# Generated by Django 2.2.2 on 2019-07-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0026_auto_20190726_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
