# Generated by Django 2.2.2 on 2019-07-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0027_auto_20190727_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parents_phone_no',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='application_no',
            field=models.CharField(default='mca_c_1', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
