# Generated by Django 2.2.2 on 2019-07-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0028_auto_20190727_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='mca', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='application_no',
            field=models.CharField(max_length=15),
        ),
    ]
