# Generated by Django 2.2.2 on 2019-08-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0030_auto_20190801_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='application_no',
        ),
    ]
