# Generated by Django 2.2.2 on 2019-08-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0031_remove_student_application_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ica_counts', models.IntegerField()),
                ('iet_counts', models.IntegerField()),
            ],
        ),
    ]
