# Generated by Django 2.2.2 on 2019-08-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0032_counts'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='counts',
            table='counts',
        ),
    ]
