# Generated by Django 2.2.2 on 2019-08-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0033_auto_20190801_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='additional_information',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
