# Generated by Django 2.2.2 on 2019-08-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0034_transaction_additional_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counts',
            old_name='iet_counts',
            new_name='mca_counts',
        ),
        migrations.AddField(
            model_name='student',
            name='batch_year',
            field=models.IntegerField(default=2017),
            preserve_default=False,
        ),
    ]
