# Generated by Django 2.2.2 on 2019-08-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0035_auto_20190803_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('subjects', models.CharField(max_length=60)),
                ('books_names', models.CharField(max_length=200)),
                ('books_msn_numbers', models.CharField(max_length=40)),
                ('books_authors', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'book_bank',
            },
        ),
    ]
