# Generated by Django 2.2.2 on 2019-08-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0036_book_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_bank',
            old_name='books_msn_numbers',
            new_name='books_ssn_numbers',
        ),
        migrations.AddField(
            model_name='book_bank',
            name='calender',
            field=models.CharField(default='w19', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_bank',
            name='stream',
            field=models.CharField(default='mca', max_length=10),
            preserve_default=False,
        ),
    ]
