# Generated by Django 2.2.2 on 2019-08-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0037_auto_20190823_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='temp',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE')], default='green', max_length=6),
        ),
    ]
