# Generated by Django 2.2.2 on 2019-09-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0039_remove_transaction_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
