# Generated by Django 2.2.2 on 2019-09-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0040_auto_20190915_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
