# Generated by Django 2.2.2 on 2019-09-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0041_auto_20190918_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='book_bank',
            unique_together={('stream', 'calender', 'semester')},
        ),
    ]
