# Generated by Django 2.2.2 on 2019-09-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0042_auto_20190920_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_bank',
            old_name='calender',
            new_name='calendar',
        ),
        migrations.AlterUniqueTogether(
            name='book_bank',
            unique_together={('stream', 'calendar', 'semester')},
        ),
    ]
