# Generated by Django 2.2.2 on 2019-09-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0045_auto_20190926_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='phone_no',
            field=models.CharField(default='9999999999', max_length=13),
            preserve_default=False,
        ),
    ]
