# Generated by Django 2.2.2 on 2019-10-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0046_auto_20190926_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transaction',
            new_name='request_transaction',
        ),
    ]
