# Generated by Django 2.2.2 on 2019-10-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0047_auto_20191007_1145'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request_transaction',
            table='request_transaction',
        ),
    ]
