# Generated by Django 2.2.2 on 2019-10-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0052_book_bank_transaction_bookbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_bank_transaction',
            name='prices',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
    ]
